version: '2'
services:
    msfconsole:
        # image: fcolista/alpine-metasploit
        build: .
        # environment:
            # DATABASE_URL: postgres://postgres@db:5432/msf
        depends_on:
            - db
        ports:
            - 4433:4433
            - 4444:4444
        volumes:
            - $HOME/.msf4:/home/msf/.msf4
        network_mode: bridge

    db:
        image: postgres:alpine
        volumes:
            - pg_data:/var/lib/postgresql/data
        network_mode: bridge

volumes:
    pg_data:
        driver: local
