version: '2'

services:
    redteam:
        image: pentest-redteam
        build:
            context: ./
            dockerfile: Dockerfile.redteam
        network_mode: host
        volumes:
            - $HOME/pentest/redteam:/root

    re:
        image: pentest-re
        build:
            context: ./
            dockerfile: Dockerfile.re
        network_mode: host
        volumes:
            - $HOME/pentest/re:/root/re
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined

    wireless:
        image: pentest-wireless
        build:
            context: ./
            dockerfile: Dockerfile.wireless
        network_mode: host
        privileged: true
        volumes:
            - $HOME/pentest/wireless:/root
