version: '2'

services:
    redteam-windows:
        image: pentest-redteam-windows
        build:
            context: ./redteam
            dockerfile: Dockerfile.windows
        network_mode: host
        privileged: true
        volumes:
            - $HOME/pentest/redteam/windows:/root/shared
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
        environment:
            - DISPLAY=$DISPLAY

    redteam-linux:
        image: pentest-redteam-linux
        build:
            context: ./redteam
            dockerfile: Dockerfile.linux
        network_mode: host
        privileged: true
        volumes:
            - $HOME/pentest/redteam/linux:/root/shared

    re:
        image: pentest-re
        build:
            context: ./
            dockerfile: Dockerfile.re
        network_mode: host
        volumes:
            - $HOME/pentest/re:/root/shared
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined

    wireless:
        image: pentest-wireless
        build:
            context: ./
            dockerfile: Dockerfile.wireless
        network_mode: host
        privileged: true
        volumes:
            - $HOME/pentest/wireless:/root/shared
