version: '2'

services:
    redteam:
        build:
            context: ./
            dockerfile: Dockerfile.redteam
        network_mode: host

    re:
        build:
            context: ./
            dockerfile: Dockerfile.re
        network_mode: host
