version: '3'
services:
    nmap:
        # image: raesene/alpine-nmap
        image: whiteoaksecurity/docker-vulscan
        network_mode: "host"
    dirb:
        build: ../../infosec/02_enumeration/dirb
        network_mode: "host"
    wpscan:
        image: wpscanteam/wpscan
        network_mode: "host"
    weevely:
        build: ../../infosec/04_persistence/weevely
        network_mode: "host"
    nikto:
        image: k0st/alpine-nikto
        network_mode: "host"
    sqlmap:
        image: k0st/alpine-sqlmap
        network_mode: "host"
        volumes:
            - $HOME/.sqlmap:/home/user/.sqlmap
