version: '2'

services:
    arduino:
        build: .
        volumes:
            - $HOME/.arduino15:/root/.arduino15
            - $HOME/Documents/Arduino:/root/Arduino
            - /dev/bus/usb:/dev/bus/usb
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY
        network_mode: host
