version: '3'

services:
    arduino:
        build: .
        volumes:
            - $HOME/.arduino15:/root/.arduino15
            - $HOME/Documents/Arduino:/root/Arduino
        environment:
            - DISPLAY=192.168.99.1:0
        network_mode: host
